ministryofjustice/hmpps-manage-adjudications

- server/data/ReportedAdjudicationResult.ts
- server/data/SecondaryLanguageResult.ts
- server/data/manageAdjudicationsClient.test.ts
- server/data/prisonApiClient.test.ts
- server/data/prisonApiClient.ts
- server/data/prisonerResult.ts
- server/routes/checkYourAnswers/checkYourAnswers.test.ts
- server/routes/confirmedOnReport/confirmedOnReport.test.ts
- server/routes/confirmedOnReport/confirmedOnReport.ts
- server/routes/incidentDetails/incidentDetails.test.ts
- server/routes/incidentStatement/incidentStatement.test.ts
- server/services/curiousApiService.test.ts
- server/services/curiousApiService.ts
- server/services/healthCheck.ts
- server/services/reportedAdjudicationsService.test.ts
- server/services/reportedAdjudicationsService.ts
- server/test/helpers.ts
> NN-3668:  Add language information to Confirmed Report page

- integration_tests/integration/incidentDetails.spec.ts
- integration_tests/integration/printReport.spec.ts
- server/routes/incidentDetails/incidentDetailsValidation.test.ts
- server/routes/incidentDetails/incidentDetailsValidation.ts
- server/routes/printReport/printReport.ts
- server/views/pages/printReport.njk
Plus fix for NN-3764 future time validation on incident details page
> NN-3802: Print report exit url swap

- integration_tests/integration/confirmedOnReport.spec.ts
- integration_tests/integration/health.spec.ts
- integration_tests/integration/notificationOfBeingPlacedOnReport.spec.ts
- integration_tests/integration/printReport.spec.ts
- integration_tests/mockApis/curiousApi.ts
- integration_tests/plugins/index.ts
- server/services/healthCheck.ts
Reverts ministryofjustice/hmpps-manage-adjudications#103
Revert until curious have there API in place on LIVE
> Revert "NN-3761: add curious api health check"

- integration_tests/integration/prisonerReport.spec.ts
- integration_tests/integration/prisonerReportReview.spec.ts
- integration_tests/pages/prisonerReport.ts
- server/routes/prisonerReport/index.ts
- server/routes/prisonerReport/prisonerReportPage.ts
- server/routes/prisonerReport/prisonerReportReview.test.ts
- server/routes/prisonerReport/prisonerReportReview.ts
- server/routes/prisonerReport/prisonerReportReviewValidation.test.ts
- server/routes/prisonerReport/prisonerReportReviewValidation.ts
- server/views/macros/adjudicationReviewPanel.njk
- server/views/macros/adjudicationSummary.njk
- server/views/pages/checkYourAnswers.njk
- server/views/pages/printReport.njk
- server/views/pages/prisonerReport.njk
- server/views/partials/reviewPanelRadios.njk
note, this ticket is UI only and is not connected to the API.  There is a seperate ticket for that
> NN-4064 review panel added to prisoner report, includes validation and UI tests

- server/data/ConfirmedOnReportData.ts
- server/data/ReportedAdjudicationResult.ts
- server/data/noticeOfBeingPlacedOnReportData.ts
- server/routes/adjudicationPdf/adjudicationPdf.test.ts
- server/routes/allCompletedReports/allCompletedReports.test.ts
- server/routes/confirmedOnReport/confirmedOnReport.test.ts
- server/routes/printReport/printReport.test.ts
- server/routes/prisonerReport/prisonerReport.test.ts
- server/routes/prisonerReport/prisonerReportReview.test.ts
- server/routes/yourCompletedReports/yourCompletedReport.test.ts
- server/services/reportedAdjudicationsService.ts
- server/views/macros/noticeOfBeingPlacedOnReportDetails.njk
changes to pdf, and all supporting reportedAdjudication results
> NN-4182 pdf change

- assets/sass/components/_details-of-offence.scss
- integration_tests/integration/detailsOfOffence.spec.ts
- integration_tests/pages/detailsOfOffence.ts
- server/routes/detailsOfOffence/detailsOfOffence.ts
- server/views/pages/detailsOfOffence.njk
note check your answers has been done prior (was listed on jira ticket)
> NN-4181 changes to offence details

- server/routes/ageOfPrisoner/ageOfPrisoner.test.ts
- server/routes/checkYourAnswers/checkYourAnswers.test.ts
..i couldn't find an easy way to check the pdf has the correct rules
> NN-4250: Add tests for prison rule in njk files

- integration_tests/integration/incidentRoleSubmittedEdit.cy.ts
- server/routes/incidentRole/incidentRolePage.test.ts
- server/routes/incidentRole/incidentRolePage.ts
- server/routes/incidentRole/incidentRoleSubmittedEdit.test.ts
Reverts ministryofjustice/hmpps-manage-adjudications#311
> Revert "NN-4358: Go to offence details page from incident role page if offences exist"

- helm_deploy/hmpps-manage-adjudications/Chart.yaml
- helm_deploy/hmpps-manage-adjudications/values.yaml
https://dsdmoj.atlassian.net/browse/NN-4333
> NN-4333: enable both ingress controllers; use latest hmpps-helm-charts

- helm_deploy/hmpps-manage-adjudications/values.yaml
https://dsdmoj.atlassian.net/browse/NN-4333
> NN-4333: remove old ingress

- package-lock.json
- package.json
Ticket created to look into this update more thoroughly and sort out the helmet config changes required - https://dsdmoj.atlassian.net/browse/NN-4601
> NN-4600: Revert helmet dep update

- helm_deploy/values-preprod.yaml
Run 2 instances in PreProd to be consistent with API https://github.com/ministryofjustice/hmpps-incentives-ui/blob/908504cd85db8c98509903a7689484badac332ea/helm_deploy/values-preprod.yaml#L5
> Run 2 instances in PreProd to be consistent with API

- integration_tests/integration/incidentDetailsEdit.cy.ts
- integration_tests/integration/incidentDetailsSubmittedEdit.cy.ts
- server/routes/incidentDetails/incidentDetails.test.ts
- server/routes/incidentDetails/incidentDetailsPage.ts
- server/routes/incidentDetails/incidentDetailsValidation.ts
> NN-4605  discovery 

- integration_tests/integration/checkYourAnswers.cy.ts
- server/services/placeOnReportService.test.ts
- server/services/placeOnReportService.ts
- server/views/pages/incidentDetails.njk
Check your answers - added Date / Time of discovery
> NN-4500 all local unit/int tests pass

- integration_tests/integration/scheduleHearing.cy.ts
- integration_tests/integration/scheduleHearingEdit.cy.ts
- integration_tests/pages/scheduleHearing.ts
- server/data/ReportedAdjudicationResult.ts
- server/routes/adjudicationTabbedParent/hearingDetails/hearingDetailsPage.ts
- server/routes/adjudicationTabbedParent/scheduleHearing/scheduleHearing.test.ts
- server/routes/adjudicationTabbedParent/scheduleHearing/scheduleHearingEdit.test.ts
- server/routes/adjudicationTabbedParent/scheduleHearing/scheduleHearingPage.ts
- server/routes/adjudicationTabbedParent/scheduleHearing/scheduleHearingValidation.test.ts
- server/routes/adjudicationTabbedParent/scheduleHearing/scheduleHearingValidation.ts
- server/views/pages/adjudicationTabbedParent/scheduleHearing.njk
Adds radio buttons for hearing type to the 'schedule hearing' page, plus associated test changes
> NN-4614: Schedule hearing update

- integration_tests/integration/checkYourAnswersBeforeChangeReporter.cy.ts
- integration_tests/integration/prisonerReport.cy.ts
- server/routes/adjudicationTabbedParent/prisonerReport/prisonerReport.test.ts
- server/routes/adjudicationTabbedParent/prisonerReport/prisonerReportReview.test.ts
- server/routes/checkYourAnswers/checkYourAnswers.test.ts
- server/routes/checkYourAnswers/checkYourAnswersBeforeChangeReporter.test.ts
- server/routes/prisonerReport/prisonerReport.test.ts
- server/routes/prisonerReport/prisonerReportReview.test.ts
ensurig consistent label naming in tests for incident/discovery
> NN-4503  - Adjudications reporter - View and amend report 

- integration_tests/integration/detailsOfOffence.cy.ts
- server/views/macros/noticeOfBeingPlacedOnReportDetails.njk
- server/views/pages/detailsOfOffence.njk
add safe to offence details and printed reported to support html line break in paragraph description
> NN-4592 NN-4593

- helm_deploy/values-dev.yaml
- server/app.ts
Stop persistent maintenance mode
> Nn 4646 switch off maintenance page

- helm_deploy/values-prod.yaml
- server/views/pages/maintenancePage.njk
https://dsdmoj.atlassian.net/browse/NN-4479
> NN-4479: update copy with time of the upgrade

- integration_tests/integration/allOffenceCodeSelection.cy.ts
- integration_tests/integration/detailsOfOffence.cy.ts
- server/offenceCodeDecisions/DecisionTree.ts
also correct committed title, to include prisoner name for endanger and fight with as per screenshots.
> NN-4519 add fight with someone

- .circleci/config.yml
- renovate.json
See https://dsdmoj.atlassian.net/browse/INC-972
> Configure Renovate to bump libraries covered by check_updated

- integration_tests/integration/allCompletedReports.cy.ts
- integration_tests/integration/yourCompletedReports.cy.ts
- server/routes/yourCompletedReports/yourCompletedReport.test.ts
- server/views/macros/adjudicationFilter.njk
- server/views/pages/allCompletedReports.njk
- server/views/pages/yourCompletedReports.njk
Note mostake in branch name - should be NN-4714 ticket
> NN-4714 - updated cypress tests

- integration_tests/integration/checkYourAnswers.cy.ts
- integration_tests/integration/deletePerson.cy.ts
- integration_tests/integration/selectGender.cy.ts
- server/routes/associatedPrisoner/associatedPrisoner.test.ts
- server/routes/associatedPrisoner/associatedPrisonerSubmittedEdit.test.ts
- server/routes/checkYourAnswers/checkYourAnswersBeforeChangeReporter.test.ts
- server/routes/deletePerson/deletePerson.test.ts
- server/routes/detailsOfOffence/deleteOffence.test.ts
- server/routes/incidentDetails/incidentDetails.test.ts
- server/routes/incidentDetails/incidentDetailsEdit.test.ts
- server/routes/incidentDetails/incidentDetailsSubmittedEdit.test.ts
- server/routes/incidentRole/incidentRole.test.ts
- server/routes/incidentRole/incidentRolePage.test.ts
- server/routes/incidentRole/incidentRoleSubmittedEdit.test.ts
- server/routes/incidentStatement/incidentStatementSubmittedEdit.test.ts
- server/routes/offenceCodeDecisions/offenceCodeDecisions.test.ts
- server/routes/selectGender/selectGender.test.ts
- server/routes/selectGender/selectGenderEdit.test.ts
- server/routes/testutils/testData.ts
Swapping test data over to use the new test data class - this PR is mainly prisoner data and a new draft adjudication function.
> NN-4722: Refactor tests

- cypress.config.ts
- integration_tests/integration/prosecution.cy.ts
- integration_tests/mockApis/adjudications.ts
- integration_tests/pages/prosecution.ts
- server/data/OutcomeResult.ts
- server/data/manageAdjudicationsClient.ts
- server/routes/index.ts
- server/routes/prosecution/index.ts
- server/routes/prosecution/prosecution.test.ts
- server/routes/prosecution/prosecution.ts
- server/routes/prosecution/prosecutionPage.ts
- server/routes/prosecution/prosecutionValidation.test.ts
- server/routes/prosecution/prosecutionValidation.ts
- server/routes/testutils/appSetup.ts
- server/services/index.ts
- server/services/outcomesService.ts
- server/utils/urlGenerator.ts
- server/views/pages/prosecution.njk
this page can be used for both "refer police" with a hearing, or without.
> NN-4782 prosecution page

- integration_tests/integration/hearingPleaAndFinding.cy.ts
- integration_tests/integration/hearingPleaAndFindingEdit.cy.ts
- integration_tests/integration/hearingTab.cy.ts
- server/data/HearingAndOutcomeResult.ts
- server/data/ReportedAdjudicationResult.ts
- server/routes/adjudicationForReport/hearingTab/hearingTabPage.ts
- server/routes/adjudicationForReport/hearingTab/hearingTabReporter.test.ts
- server/routes/adjudicationForReport/hearingTab/hearingTabReviewer.test.ts
- server/routes/hearingOutcome/pleaAndFinding/pleaAndFinding.test.ts
- server/routes/hearingOutcome/pleaAndFinding/pleaAndFindingEdit.test.ts
- server/routes/testutils/testData.ts
- server/services/reportedAdjudicationsService.ts
- server/utils/nunjucksSetup.ts
- server/utils/utils.ts
- server/views/macros/hearingSummary.njk
- server/views/pages/adjudicationForReport/hearingTab.njk
- server/views/pages/hearingOutcome/pleaAndFinding.njk
- server/views/partials/hearingDetailsVariations/hearingTable.njk
- server/views/partials/hearingDetailsVariations/hearingTableExpansions/hearingTableAdjourn.njk
- server/views/partials/hearingDetailsVariations/hearingTableExpansions/hearingTableComplete.njk
- server/views/partials/hearingDetailsVariations/hearingTableExpansions/hearingTableCompleteDismissed.njk
- server/views/partials/hearingDetailsVariations/hearingTableExpansions/hearingTableCompleteNotProceed.njk
- server/views/partials/hearingDetailsVariations/hearingTableExpansions/hearingTableCompleteProved.njk
- server/views/partials/hearingDetailsVariations/hearingTableExpansions/hearingTableReferInAdExpansion.njk
- server/views/partials/hearingDetailsVariations/hearingTableExpansions/hearingTableReferPoliceExpansion.njk
- server/views/partials/hearingDetailsVariations/outcomeTable.njk
- changed 'history' key to 'outcomes'
- changed enum to NOT_PROCEED (previously NOT_PROCEED_WITH)
- refactor the hearings table to format data within njk, and to use partials
> NN-4892: Refactor hearings table

- server/middleware/populateCurrentUser.ts
- server/middleware/setUpAuthentication.ts
Reverts ministryofjustice/hmpps-manage-adjudications#534
> Revert "NN-4929 experiment to reduce auth calls"

- integration_tests/integration/cautionEdit.cy.ts
- integration_tests/integration/damagesOwedEdit.cy.ts
- integration_tests/integration/punishmentsAndDamages.cy.ts
- integration_tests/pages/punishmentsAndDamages.ts
- server/routes/adjudicationForReport/punishmentsTab/punishmentsTabPage.ts
- server/routes/hearingOutcome/caution/cautionEdit.test.ts
- server/routes/hearingOutcome/caution/cautionEdit.ts
- server/routes/hearingOutcome/caution/cautionPage.ts
- server/routes/hearingOutcome/caution/index.ts
- server/routes/hearingOutcome/damagesOwed/damagesOwedEdit.test.ts
- server/routes/hearingOutcome/damagesOwed/damagesOwedPage.ts
- server/routes/index.ts
- server/services/hearingsService.ts
- server/utils/urlGenerator.ts
- server/views/macros/hearingDamagesAndCautionSummary.njk
- server/views/pages/adjudicationForReport/punishmentsTab.njk
fixes for the reportNo as a param, tests (certain fields are no longer required on edit) and punishmentsPage
> NN-4954 is caution edit

- server/utils/azureAppInsights.ts
- server/utils/azureAppinsights.test.ts
https://dsdmoj.atlassian.net/browse/NN-5069
Copied/adapted from https://github.com/ministryofjustice/hmpps-incentives-ui/pull/466
> NN-5069: add user to request in App insights

- server/utils/azureAppInsights.ts
Reverts ministryofjustice/hmpps-manage-adjudications#630
> Revert "NN-5152 add line back to see if traces works"

- cypress.config.ts
- integration_tests/integration/home.cy.ts
- integration_tests/mockApis/adjudications.ts
- integration_tests/pages/home.ts
- server/data/manageAdjudicationsClient.ts
- server/routes/homepage/homepage.test.ts
- server/routes/homepage/homepage.ts
- server/routes/homepage/index.ts
- server/routes/index.ts
- server/services/reportedAdjudicationsService.ts
transferTotal can be implemented when the new link and table filter is added
> NN-5212 reports counts, only expose review for now

- server/routes/adjudicationForReport/punishmentsTab/index.ts
- server/routes/adjudicationForReport/punishmentsTab/punishmentsTabPage.ts
- server/routes/adjudicationForReport/punishmentsTab/punishmentsTabReviewer.ts
- server/routes/adjudicationForReport/punishmentsTab/punishmentsTabView.ts
need to sort out test coverage for these tabs, presumably can do this as part of some e2e tests for the full transfer feature.
Currently getting a 404 in dev due to missing route
> NN-5193 add view only route

- assets/js/displayChart.js
- assets/js/loadChart.js
- assets/sass/components/_data-insight.scss
- integration_tests/integration/dataInsights.cy.ts
- server/routes/dataInsights/chartService.ts
- server/routes/dataInsights/offenceTypeTab/offenceTypeTabPage.ts
- server/routes/dataInsights/pleasAndFindingsTab/pleasAndFindingsTabPage.ts
- server/routes/dataInsights/protectedCharacteristicsAndVulnerabilitiesTab/protectedCharacteristicsAndVulnerabilitiesTabPage.ts
- server/routes/dataInsights/punishmentsTab/punishmentsTabPage.ts
- server/routes/dataInsights/totalsAdjudicationsAndLocationsTab/totalsAdjudicationsAndLocationsTabPage.ts
- server/services/ChartDetailsResult.ts
- server/views/macros/dataInsights/horizontalBarsChartData.njk
- server/views/macros/dataInsights/verticalBarsAndLineChartData.njk
- server/views/pages/dataInsights/offenceTypeTab.njk
- server/views/pages/dataInsights/pleasAndFindingsTab.njk
- server/views/pages/dataInsights/protectedCharacteristicsAndVulnerabilitiesTab.njk
- server/views/pages/dataInsights/punishmentsTab.njk
- server/views/pages/dataInsights/totalsAdjudicationsAndLocationsTab.njk
- server/views/partials/chart.njk
- server/views/partials/charts/horizontalBarsChart.njk
- server/views/partials/charts/verticalBarsAndLineChart.njk
NN-5246: 1d - Total number of adjudications by location of rule-breaking offence;
NN-5247: 1f - Total number of adjudications by residential location of offender;
- horizontal bars chart created, reused for 1d and 1f;
> NN-5246, NN-5247

- assets/sass/components/_data-insight.scss
- integration_tests/integration/dataInsights.cy.ts
- integration_tests/pages/home.ts
- server/routes/dataInsights/chartService.ts
- server/routes/dataInsights/punishmentsTab/punishments.test.ts
- server/routes/dataInsights/punishmentsTab/punishmentsTabPage.ts
- server/services/ChartDetailsResult.ts
- server/views/macros/dataInsights/multiVerticalBarsChartData.njk
- server/views/pages/dataInsights/punishmentsTab.njk
- server/views/partials/charts/multiVerticalBarsChart.njk
- 4c multi vertical bars chart created;
> NN-5297: Block 4 - Punishments - Render all Charts;

- integration_tests/integration/awardPunishmentsStartAndEdit.cy.ts
- server/data/PunishmentResult.ts
- server/views/macros/awardPunishmentsTable.njk
https://dsdmoj.atlassian.net/browse/NN-5266
> NN-5266: Award punishments page

- integration_tests/integration/manuallyActivateSuspendedPunishment.cy.ts
- server/routes/additionalDays/numberOfAdditionalDays/index.ts
- server/routes/additionalDays/numberOfAdditionalDays/numberOfAdditionalDaysManualEdit.test.ts
- server/routes/additionalDays/numberOfAdditionalDays/numberOfAdditionalDaysManualEdit.ts
- server/routes/additionalDays/numberOfAdditionalDays/numberOfAdditionalDaysPage.ts
- server/routes/punishments/manuallyActivateSuspendedPunishments/manuallyActivateSuspendedPunishments.test.ts
- server/routes/punishments/manuallyActivateSuspendedPunishments/manuallyActivateSuspendedPunishmentsPage.ts
- server/utils/urlGenerator.ts
https://dsdmoj.atlassian.net/browse/NN-5289
> NN-5289: added days for manual suspended punishment

- cypress.config.ts
- integration_tests/integration/health.cy.ts
- integration_tests/mockApis/curiousApi.ts
- server/services/healthCheck.ts
https://dsdmoj.atlassian.net/browse/NN-5055
> NN-5055: remove CuriousAPI from /health checks

- assets/sass/components/_data-insight.scss
- server/routes/dataInsights/chartService.ts
- server/views/macros/dataInsights/giveFeedbackBanner.njk
- server/views/pages/dataInsights/offenceTypeTab.njk
- server/views/pages/dataInsights/pleasAndFindingsTab.njk
- server/views/pages/dataInsights/protectedAndResponsivityCharacteristicsTab.njk
- server/views/pages/dataInsights/punishmentsTab.njk
- server/views/pages/dataInsights/totalsAdjudicationsAndLocationsTab.njk
- feedback banner added with mailto e-mail;
> NN-5340: UI tidyups;

- server/views/pages/dataInsights/protectedAndResponsivityCharacteristicsTab.njk
> NN-5406: Block 2 - Add link to 'learning disability' and 'maturity' content;

- server/data/manageAdjudicationsClient.ts
- server/services/punishmentsService.ts
https://dsdmoj.atlassian.net/browse/NN-5444
> NN-5444: use amendPunishmentsV2

- server/data/ReportedAdjudicationResult.ts
- server/routes/adjudicationForReport/punishmentsTab/index.ts
- server/routes/adjudicationForReport/punishmentsTab/punishmentsTabPage.ts
- server/routes/adjudicationForReport/punishmentsTab/punishmentsTabReporter.ts
- server/routes/adjudicationForReport/punishmentsTab/punishmentsTabReviewer.ts
- server/routes/adjudicationForReport/punishmentsTab/punishmentsTabView.ts
- server/services/punishmentsService.ts
- server/services/reportedAdjudicationsService.ts
- server/views/pages/adjudicationForReport/punishmentsTab.njk
https://dsdmoj.atlassian.net/browse/NN-5404
> NN-5404: use getReportedAdjudicationV2 and hide editable damages and caution sections

- server/data/PunishmentResult.ts
- server/routes/punishment/punishmentPage.ts
https://dsdmoj.atlassian.net/browse/NN-5324
> NN-5324: map damagesOwedAmount

- feature.env
- helm_deploy/values-dev.yaml
- helm_deploy/values-preprod.yaml
- helm_deploy/values-prod.yaml
- integration_tests/integration/home.cy.ts
- server/config.ts
- server/routes/dataInsights/dataInsightsTabsOptions.ts
- server/routes/dataInsights/offenceTypeTab/offenceType.test.ts
- server/routes/dataInsights/offenceTypeTab/offenceType.ts
- server/routes/dataInsights/pleasAndFindingsTab/pleasAndFindings.test.ts
- server/routes/dataInsights/pleasAndFindingsTab/pleasAndFindings.ts
- server/routes/dataInsights/protectedAndResponsivityCharacteristicsTab/protectedAndResponsivityCharacteristics.test.ts
- server/routes/dataInsights/protectedAndResponsivityCharacteristicsTab/protectedAndResponsivityCharacteristics.ts
- server/routes/dataInsights/punishmentsTab/punishments.test.ts
- server/routes/dataInsights/punishmentsTab/punishments.ts
- server/routes/dataInsights/totalsAdjudicationsAndLocationsTab/dataInsights.test.ts
- server/routes/dataInsights/totalsAdjudicationsAndLocationsTab/totalsAdjudicationsAndLocations.test.ts
- server/routes/dataInsights/totalsAdjudicationsAndLocationsTab/totalsAdjudicationsAndLocations.ts
- server/routes/homepage/homepage.ts
- server/routes/index.ts
https://dsdmoj.atlassian.net/browse/NN-5174
> NN-5174: remove DATA_INSIGHTS_FLAG and caseload check

- server/routes/dataInsights/chartService.ts
- server/routes/dataInsights/punishmentsTab/punishmentsTabPage.ts
https://dsdmoj.atlassian.net/browse/NN-5468
> NN-5468: update chart 4c's table total label

- server/routes/dataInsights/pleasAndFindingsTab/pleasAndFindingsTabPage.ts
- server/views/pages/dataInsights/pleasAndFindingsTab.njk
https://dsdmoj.atlassian.net/browse/NN-5466
> NN-5466: re-add hidden chart '5c'

- integration_tests/integration/dataInsights.cy.ts
- server/routes/dataInsights/chartService.ts
- server/routes/dataInsights/punishmentsTab/punishmentsTabPage.ts
- server/routes/dataInsights/totalsAdjudicationsAndLocationsTab/totalsAdjudicationsAndLocationsTabPage.ts
- server/services/ChartDetailsResult.ts
- server/views/macros/dataInsights/commentaryChartData.njk
- server/views/pages/dataInsights/punishmentsTab.njk
https://dsdmoj.atlassian.net/browse/NN-5467
> NN-5467: add commentary '4d'

- server/routes/dataInsights/punishmentsTab/punishmentsTabPage.ts
https://dsdmoj.atlassian.net/browse/NN-5468
> NN-5468: use sentence case

- integration_tests/integration/notificationOfBeingPlacedOnReport.cy.ts
- integration_tests/integration/printCompletedDIS12Forms.cy.ts
- integration_tests/integration/printDis12Report.cy.ts
- server/routes/adjudicationForReport/prisonerReport/prisonerReportPage.ts
- server/routes/disPdf/dis12Pdf.test.ts
- server/routes/disPdf/dis12Pdf.ts
- server/routes/disPdf/index.ts
- server/routes/index.ts
- server/routes/printReport/index.ts
- server/routes/printReport/printDis12Report.test.ts
- server/routes/printReport/printDis12Report.ts
- server/utils/urlGenerator.ts
- server/views/pages/printCompletedDIS12Forms.njk
- server/views/pages/printDis12Report.njk
https://dsdmoj.atlassian.net/browse/NN-5040
> NN-5040: refactor classes and routes to be DIS 1/2 specific ahead of adding additional DIS reports

- assets/sass/components/_adjudication-pdf.scss
- server/data/ConfirmedOnReportData.ts
- server/data/adjudicationHistoryForCurrentSentenceData.ts
- server/routes/disPdf/dis5Pdf.test.ts
- server/routes/disPdf/dis5Pdf.ts
- server/routes/disPdf/index.ts
- server/services/reportedAdjudicationsService.test.ts
- server/services/reportedAdjudicationsService.ts
- server/utils/urlGenerator.ts
- server/views/macros/adjudicationHistoryForCurrentSentenceDetails.njk
- server/views/macros/adjudicationHistoryForCurrentSentenceExistingPunishments.njk
- server/views/macros/adjudicationHistoryForCurrentSentencePreviousAdjudication.njk
- server/views/macros/adjudicationHistoryForCurrentSentenceSuspendedPunishments.njk
- server/views/pages/adjudicationHistoryForCurrentSentence.njk
- server/views/pages/adjudicationHistoryForCurrentSentenceFooter.njk
- server/views/pages/adjudicationHistoryForCurrentSentenceHeader.njk
https://dsdmoj.atlassian.net/browse/NN-4854
> NN-4854: DIS5

- assets/sass/components/_adjudication-pdf.scss
- server/data/conductReportData.ts
- server/routes/disPdf/dis6Pdf.test.ts
- server/routes/disPdf/dis6Pdf.ts
- server/routes/disPdf/index.ts
- server/utils/urlGenerator.ts
- server/views/macros/conductReportDetails.njk
- server/views/pages/conductReport.njk
- server/views/pages/conductReportFooter.njk
- server/views/pages/conductReportHeader.njk
https://dsdmoj.atlassian.net/browse/NN-4855
> NN-4855: DIS6

- assets/sass/components/_adjudication-pdf.scss
- server/data/adjudicationResultReportData.ts
- server/routes/disPdf/dis7Pdf.test.ts
- server/routes/disPdf/dis7Pdf.ts
- server/routes/disPdf/index.ts
- server/utils/urlGenerator.ts
- server/views/macros/adjudicationResultReportDetails.njk
- server/views/macros/adjudicationResultReportLegal.njk
- server/views/pages/adjudicationResultReport.njk
- server/views/pages/adjudicationResultReportFooter.njk
- server/views/pages/adjudicationResultReportHeader.njk
https://dsdmoj.atlassian.net/browse/NN-4856
https://dsdmoj.atlassian.net/browse/NN-4857
> NN-4856 NN-4857: DIS7

- integration_tests/integration/formsTab.cy.ts
- server/data/ReportedAdjudicationResult.ts
- server/routes/testutils/testData.ts
- server/services/reportedAdjudicationsService.test.ts
- server/services/reportedAdjudicationsService.ts
- server/views/pages/adjudicationForReport/formsTab.njk
https://dsdmoj.atlassian.net/browse/NN-5381
> NN-5381: display DIS 1/2 form issue history

- cypress.config.ts
- integration_tests/integration/createOnBehalfOf.cy.ts
- integration_tests/mockApis/adjudications.ts
- integration_tests/pages/checkCreateOnBehalfOf.ts
- server/data/DraftAdjudicationResult.ts
- server/data/ReportedAdjudicationResult.ts
- server/data/manageAdjudicationsSystemTokensClient.ts
- server/routes/createOnBehalfOf/checkCreateOnBehalfOf.test.ts
- server/routes/createOnBehalfOf/checkCreateOnBehalfOf.ts
- server/routes/createOnBehalfOf/checkCreateOnBehalfOfPage.ts
- server/routes/createOnBehalfOf/index.ts
- server/routes/index.ts
- server/routes/testutils/testData.ts
- server/services/placeOnReportService.ts
- server/utils/urlGenerator.ts
- server/views/macros/summaryListWithChangeLinks.njk
- server/views/pages/checkCreateOnBehalfOf.njk
https://dsdmoj.atlassian.net/browse/NN-5542
I created the endpoint with https://github.com/ministryofjustice/hmpps-manage-adjudications-api/pull/525 and started the UI changes from _Check your answers_ hence this PR having hardcoded data
> NN-5542: creating reports on behalf of someone else - Check your answers

- cypress.config.ts
- integration_tests/integration/createOnBehalfOf.cy.ts
- integration_tests/pages/checkCreateOnBehalfOf.ts
- integration_tests/pages/createOnBehalfOf.ts
- integration_tests/pages/createOnBehalfOfReason.ts
- server/@types/express/index.d.ts
- server/routes/createOnBehalfOf/checkCreateOnBehalfOf.test.ts
- server/routes/createOnBehalfOf/checkCreateOnBehalfOf.ts
- server/routes/createOnBehalfOf/checkCreateOnBehalfOfPage.ts
- server/routes/createOnBehalfOf/checkOnBehalfOfSessionService.ts
- server/routes/createOnBehalfOf/createOnBehalfOf.test.ts
- server/routes/createOnBehalfOf/createOnBehalfOf.ts
- server/routes/createOnBehalfOf/createOnBehalfOfPage.ts
- server/routes/createOnBehalfOf/createOnBehalfOfReason.test.ts
- server/routes/createOnBehalfOf/createOnBehalfOfReason.ts
- server/routes/createOnBehalfOf/createOnBehalfOfReasonPage.ts
- server/routes/createOnBehalfOf/createOnBehalfOfReasonValidation.test.ts
- server/routes/createOnBehalfOf/createOnBehalfOfReasonValidation.ts
- server/routes/createOnBehalfOf/createOnBehalfOfSessionService.ts
- server/routes/createOnBehalfOf/createOnBehalfOfValidation.test.ts
- server/routes/createOnBehalfOf/createOnBehalfOfValidation.ts
- server/routes/createOnBehalfOf/index.ts
- server/routes/index.ts
- server/routes/testutils/appSetup.ts
- server/services/index.ts
- server/utils/urlGenerator.ts
- server/views/pages/checkCreateOnBehalfOf.njk
- server/views/pages/createOnBehalfOf.njk
- server/views/pages/createOnBehalfOfReason.njk
https://dsdmoj.atlassian.net/browse/NN-5540
https://dsdmoj.atlassian.net/browse/NN-5541
> NN-5540 NN-5541: creating reports on behalf of someone else - user entry and submit

- server/views/macros/adjudicationHistoryForCurrentSentenceDetails.njk
https://dsdmoj.atlassian.net/browse/NN-4894
> NN-4894: include additional question

- assets/sass/components/_adjudication-pdf.scss
- server/data/adjudicationHistoryForCurrentSentenceData.ts
- server/data/adjudicationResultReportData.ts
- server/data/conductReportData.ts
- server/routes/disPdf/dis5Pdf.test.ts
- server/routes/disPdf/dis6Pdf.test.ts
- server/routes/disPdf/dis7Pdf.test.ts
- server/routes/homepage/homepage.ts
- server/views/macros/adjudicationHistoryForCurrentSentenceDetails.njk
- server/views/macros/adjudicationResultReportDetails.njk
- server/views/macros/conductReportDetails.njk
- server/views/macros/prepareAndRecordAnAdjudicationHearingPrepare.njk
https://dsdmoj.atlassian.net/browse/NN-5562
> NN-5562: apply a consistent pattern to prisoner information in DIS forms

- integration_tests/integration/awardedPunishmentsAndDamages.cy.ts
- integration_tests/pages/awardedPunishmentsAndDamages.ts
- integration_tests/pages/home.ts
- server/data/ReportedAdjudicationResult.ts
- server/routes/homepage/homepage.ts
- server/routes/index.ts
- server/routes/punishments/awardedPunishmentsAndDamages/awardedPunishmentsAndDamages.test.ts
- server/routes/punishments/awardedPunishmentsAndDamages/awardedPunishmentsAndDamages.ts
- server/routes/punishments/awardedPunishmentsAndDamages/index.ts
- server/services/reportedAdjudicationsService.ts
- server/utils/adjudicationFilterHelper.ts
- server/utils/urlGenerator.ts
- server/views/macros/awardedPunishmentsAndDamagesTabHeader.njk
- server/views/macros/hearingsAndResidentalLocationFilter.njk
- server/views/pages/awardedPunishmentsAndDamages/awardedPunishmentsAndDamages.njk
https://dsdmoj.atlassian.net/browse/NN-5377
https://dsdmoj.atlassian.net/browse/NN-5545
> NN-5377 NN-5545: view awarded punishments and damages

- integration_tests/integration/awardedPunishmentsAndDamages.cy.ts
- integration_tests/pages/additionalDaysAwardedPunishments.ts
- integration_tests/pages/awardedPunishmentsAndDamages.ts
- integration_tests/pages/financialAwardedPunishmentsAndDamages.ts
- server/data/ReportedAdjudicationResult.ts
- server/routes/punishments/awardedPunishmentsAndDamages/additionalDaysAwardedPunishments.test.ts
- server/routes/punishments/awardedPunishmentsAndDamages/additionalDaysAwardedPunishments.ts
- server/routes/punishments/awardedPunishmentsAndDamages/financialAwardedPunishmentsAndDamages.test.ts
- server/routes/punishments/awardedPunishmentsAndDamages/financialAwardedPunishmentsAndDamages.ts
- server/routes/punishments/awardedPunishmentsAndDamages/index.ts
- server/services/reportedAdjudicationsService.ts
- server/utils/urlGenerator.ts
- server/views/pages/awardedPunishmentsAndDamages/additionalDaysAwardedPunishments.njk
- server/views/pages/awardedPunishmentsAndDamages/financialAwardedPunishmentsAndDamages.njk
https://dsdmoj.atlassian.net/browse/NN-5546
https://dsdmoj.atlassian.net/browse/NN-5547
> NN-5546 NN-5547: Punishment summary - Finance & Additional days

- integration_tests/integration/awardPunishmentsStartAndEdit.cy.ts
- server/data/PunishmentResult.ts
- server/views/macros/punishmentRadios.njk
https://dsdmoj.atlassian.net/browse/NN-5565
> NN-5565: add PrivilegeType.GYM

- server/utils/azureAppInsights.ts
https://dsdmoj.atlassian.net/browse/NN-5069
It was accidentally removed with https://github.com/ministryofjustice/hmpps-manage-adjudications/pull/644/files#diff-4284cd29c30aa1654eae749db22b117d0a62daa7815636848b413f033528d739L38
> NN-5069: re-add user to request in App insights

- integration_tests/integration/dataInsights.cy.ts
- integration_tests/pages/dataInsights.ts
- server/routes/dataInsights/protectedAndResponsivityCharacteristicsTab/protectedAndResponsivityCharacteristicsTabPage.ts
- server/views/pages/dataInsights/protectedAndResponsivityCharacteristicsTab.njk
https://dsdmoj.atlassian.net/browse/NN-5563
> NN-5563: small tweaks to PC page; int tests to cover switching PC pages

- server/views/pages/dataInsights/protectedAndResponsivityCharacteristicsTab.njk
https://dsdmoj.atlassian.net/browse/NN-5563
> NN-5563: bump PC evidence links section headers to h2

- integration_tests/integration/awardedPunishmentsAndDamages.cy.ts
- integration_tests/integration/home.cy.ts
- integration_tests/pages/additionalDaysAwardedPunishments.ts
- integration_tests/pages/awardedPunishmentsAndDamages.ts
- integration_tests/pages/financialAwardedPunishmentsAndDamages.ts
- integration_tests/pages/home.ts
- server/routes/homepage/homepage.test.ts
- server/routes/homepage/homepage.ts
- server/routes/punishments/awardedPunishmentsAndDamages/additionalDaysAwardedPunishments.test.ts
- server/routes/punishments/awardedPunishmentsAndDamages/awardedPunishmentsAndDamages.test.ts
- server/routes/punishments/awardedPunishmentsAndDamages/financialAwardedPunishmentsAndDamages.test.ts
- server/views/macros/adjudicationTabHeaderAll.njk
- server/views/pages/awardedPunishmentsAndDamages/additionalDaysAwardedPunishments.njk
- server/views/pages/awardedPunishmentsAndDamages/awardedPunishmentsAndDamages.njk
- server/views/pages/awardedPunishmentsAndDamages/financialAwardedPunishmentsAndDamages.njk
https://dsdmoj.atlassian.net/browse/NN-5574
> NN-5574: update homepage and sub-navigation links

- server/views/pages/printCompletedDIS12Forms.njk
https://dsdmoj.atlassian.net/browse/NN-5585
> NN-5585: tweak hidden text on print-completed-DIS-forms page

- server/views/macros/noticeOfBeingPlacedOnReportLegal.njk
https://dsdmoj.atlassian.net/browse/NN-5502
> NN-5502: design review comments

- server/routes/adjudicationForReport/hearingTab/hearingTabPage.ts
- server/routes/adjudicationForReport/prisonerReport/prisonerReportPage.ts
- server/routes/adjudicationForReport/punishmentsTab/punishmentsTabPage.ts
- server/services/reportedAdjudicationsService.ts
https://dsdmoj.atlassian.net/browse/NN-5665
> NN-5665: Add extra check on report status

- docker-compose-test.yml
- docker-compose.yml
- helm_deploy/hmpps-manage-adjudications/values.yaml
Reverts ministryofjustice/hmpps-manage-adjudications#952
> Revert "Update gotenberg/gotenberg Docker tag to v8"

- server/views/pages/completeRehabilitativeActivity.njk
Reverts ministryofjustice/hmpps-manage-adjudications#1116
> Revert "rename label"

- .circleci/config.yml
Reverts ministryofjustice/hmpps-manage-adjudications#1139
> Revert "update context"

- .husky/pre-commit
- package-lock.json
- package.json
Updated husky
Corrected pre-commit and npm command
> NN-5969 Update husky

- assets/sass/components/_card.scss
> NN-5970 - Deprecated SASS

- .circleci/config.yml
- Dockerfile
- docker-compose-test.yml
- docker-compose.yml
- helm_deploy/hmpps-manage-adjudications/Chart.yaml
- helm_deploy/hmpps-manage-adjudications/values.yaml
Updated Node.js and all other non Node.js dependencies / requirements
Upgrade Node.js
Updated helm charts
Updated orbs
Updated Gotenberg
Updated Redis
> NN-5971 - NN-5973 - Update Node.js and Orbs

- package-lock.json
- package.json
> fixed denial of service vulnerability in body-parser

- package-lock.json
> fixed path-to-regexp: Backtracking regular expressions

- server/views/macros/noticeOfBeingPlacedOnReportLegal.njk
https://dsdmoj.atlassian.net/browse/NN-5982
> changed some text for policy

- server/views/macros/noticeOfBeingPlacedOnReportDetails.njk
https://dsdmoj.atlassian.net/browse/NN-5884
> DIS 1: where a hearing has been scheduled, add the date and time to the form

- server/routes/disPdf/dis12Pdf.ts
adding log to see if noticeOfBeingPlacedOnReportData.nextHearingTime is returned for scheduled hearing
> added some log

- server/routes/disPdf/dis12Pdf.ts
adding log to see the value of reportedAdjudication.status and ReportedAdjudicationStatus.SCHEDULED
> Dis 1 troubleshooting

- package-lock.json
- package.json
Upgrading Adjudication frontend to use the latest MOJ frontend, version 3.0.3
https://dsdmoj.atlassian.net/browse/NN-5993
> updated ministryofjustice/frontend from v2.2.5 to v3.0.3

- server/routes/disPdf/dis12Pdf.ts
- server/views/macros/noticeOfBeingPlacedOnReportDetails.njk
Reversed this task ===> https://dsdmoj.atlassian.net/browse/NN-5884
> reverted DIS 1 changes

- .circleci/config.yml
- package-lock.json
- package.json
> Upgrade Node.js

- cypress.config.ts
- integration_tests/integration/govReferralE2e.cy.ts
- integration_tests/integration/scheduleHearing.cy.ts
- integration_tests/mockApis/prisonApi.ts
These tests relate to prison-api endpoints that no longer called
> MAP-1808 remove unused code
